---
general:
  buildTool: "mta"

stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Additional Unit Tests:
    npmExecuteScripts: false
    karmaExecuteTests: false
  Acceptance:
    cloudFoundryDeploy: false
#   cfApiEndpoint: "<%= cfapi %>"
#   cfOrg: "<%= cforg %>"
#   cfSpace: "<%= cfspace %>"
#   cfAppName: "<%= projectName %>"
#   cfCredentialsId: "deploy-to-cf"
    uiVeri5ExecuteTests: false
  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "<%= cfapi %>"
    cfOrg: "<%= cforg %>"
    cfSpace: "<%= cfspace %>"
    cfAppName: "<%= projectName %>"
    cfCredentialsId: "deploy-to-cf"
    tmsUpload: true

steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "<%= cfspace %>"
    credentialsId: "tms-sk"
    customDescription: "<%= projectName %> : <%= displayName %>"
